require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CamerasController do

  # This should return the minimal set of attributes required to create a valid
  # Camera. As you add validations to Camera, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CamerasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cameras as @cameras" do
      camera = Camera.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cameras).should eq([camera])
    end
  end

  describe "GET show" do
    it "assigns the requested camera as @camera" do
      camera = Camera.create! valid_attributes
      get :show, {:id => camera.to_param}, valid_session
      assigns(:camera).should eq(camera)
    end
  end

  describe "GET new" do
    it "assigns a new camera as @camera" do
      get :new, {}, valid_session
      assigns(:camera).should be_a_new(Camera)
    end
  end

  describe "GET edit" do
    it "assigns the requested camera as @camera" do
      camera = Camera.create! valid_attributes
      get :edit, {:id => camera.to_param}, valid_session
      assigns(:camera).should eq(camera)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Camera" do
        expect {
          post :create, {:camera => valid_attributes}, valid_session
        }.to change(Camera, :count).by(1)
      end

      it "assigns a newly created camera as @camera" do
        post :create, {:camera => valid_attributes}, valid_session
        assigns(:camera).should be_a(Camera)
        assigns(:camera).should be_persisted
      end

      it "redirects to the created camera" do
        post :create, {:camera => valid_attributes}, valid_session
        response.should redirect_to(Camera.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved camera as @camera" do
        # Trigger the behavior that occurs when invalid params are submitted
        Camera.any_instance.stub(:save).and_return(false)
        post :create, {:camera => {}}, valid_session
        assigns(:camera).should be_a_new(Camera)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Camera.any_instance.stub(:save).and_return(false)
        post :create, {:camera => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested camera" do
        camera = Camera.create! valid_attributes
        # Assuming there are no other cameras in the database, this
        # specifies that the Camera created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Camera.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => camera.to_param, :camera => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested camera as @camera" do
        camera = Camera.create! valid_attributes
        put :update, {:id => camera.to_param, :camera => valid_attributes}, valid_session
        assigns(:camera).should eq(camera)
      end

      it "redirects to the camera" do
        camera = Camera.create! valid_attributes
        put :update, {:id => camera.to_param, :camera => valid_attributes}, valid_session
        response.should redirect_to(camera)
      end
    end

    describe "with invalid params" do
      it "assigns the camera as @camera" do
        camera = Camera.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Camera.any_instance.stub(:save).and_return(false)
        put :update, {:id => camera.to_param, :camera => {}}, valid_session
        assigns(:camera).should eq(camera)
      end

      it "re-renders the 'edit' template" do
        camera = Camera.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Camera.any_instance.stub(:save).and_return(false)
        put :update, {:id => camera.to_param, :camera => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested camera" do
      camera = Camera.create! valid_attributes
      expect {
        delete :destroy, {:id => camera.to_param}, valid_session
      }.to change(Camera, :count).by(-1)
    end

    it "redirects to the cameras list" do
      camera = Camera.create! valid_attributes
      delete :destroy, {:id => camera.to_param}, valid_session
      response.should redirect_to(cameras_url)
    end
  end

end
